import Link from "next/link";
import "./globals.css";
import type { Metadata } from "next";
import { Topic } from "./model/model";
import Control from "./Control";

export const metadata: Metadata = {
  title: "Web tutorials",
  description: "Generated by smkim",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const res = await fetch("http://localhost:9999/topics", {
    next: { revalidate: 0 },
  });
  // ,{cache:'no-store'},);
  const topics = await res.json();

  /*
  //client component만 가능 
  const [topics, setTopics] = useState([]);
  useState(() => {
    fetch("http://localhost:9999/topics")
      .then((res) => res.json())
      .then((result) => setTopics(result));
  }, []);
  */
  return (
    <html>
      <body>
        <h1>
          <Link href="/" prefetch={false}>
            WEB
          </Link>
        </h1>
        <ol>
          {topics.map((topic: Topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`} prefetch={false}>
                  {topic.title}
                </Link>
              </li>
            );
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
